# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np

In [3]:
ar = np.arange(start = 0, stop = 99, step = 1)

In [4]:
ar*0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 2.Создать вектор размера 100, заполненный единицами

In [10]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [11]:
np.full(100,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [13]:
import numpy;

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [14]:
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

#### 6. Создать вектор со значениями от 10 до 100

In [16]:
np.arange(10,101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### 7. Развернуть вектор (первый становится последним)

In [19]:
v = np.arange(10)

In [20]:
v[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [24]:
v = np.array([1,2,3,4,5])
nz = 3

In [ ]:
v0 = np.zeros(len(v) + (len(v)-1)*(nz))

In [25]:
v0[::nz+1] = v

SyntaxError: keyword can't be an expression (<ipython-input-25-08306e994bc4>, line 1)

In [26]:
v0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [28]:
np.random.random((3,3,3))

array([[[0.60044646, 0.15334158, 0.41200821],
        [0.29191646, 0.54914295, 0.77380267],
        [0.86911664, 0.35841917, 0.82691272]],

       [[0.89800045, 0.10577018, 0.09114375],
        [0.13922431, 0.24484497, 0.88608192],
        [0.19457094, 0.67745106, 0.73439917]],

       [[0.24184113, 0.89757436, 0.41256128],
        [0.02063628, 0.7273838 , 0.40200219],
        [0.53552797, 0.36522399, 0.21223943]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [37]:
v = np.random.random((10,10))

In [38]:
vmin = v.min()

In [39]:
vmax =  v.max()

In [40]:
vmin

0.014848587192254903

In [41]:
vmax

0.9963448004953482

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [42]:
np.random.random(30).mean()

0.4569183367933336

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [43]:
v = np.ones((10,10))

In [44]:
v[1:-1,1:-1] = 0

In [45]:
v

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [48]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [50]:
v = np.zeros((8,8), dtype=int)

In [51]:
v[1::2,::2] = 1

In [52]:
v[::2,1::2] = 1

In [53]:
v

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [54]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [56]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [57]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [58]:
v = np.arange(100)

In [59]:
v[(3 < v) & (v <= 8)] *= -1

In [60]:
v

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [61]:
v = np.zeros((5,5))

In [62]:
v += np.arange(5)

In [63]:
v

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 24. Есть генератор, сделать с его помощью массив

In [67]:
def fun():
    for x in range(100):
        yield x

In [68]:
v = np.fromiter(fun(),dtype=float,count=-1)

In [69]:
v

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [70]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [81]:
v = np.random.random(100)

In [82]:
v.sort()

In [83]:
v

array([0.02782129, 0.03166561, 0.04223952, 0.0625892 , 0.06403072,
       0.06438396, 0.0731401 , 0.07864907, 0.0867663 , 0.08731575,
       0.08922199, 0.11157588, 0.12042023, 0.12135966, 0.14815262,
       0.15514358, 0.19010929, 0.19208966, 0.20837096, 0.22220109,
       0.23225982, 0.23382624, 0.25561531, 0.26511195, 0.26548487,
       0.2713798 , 0.27386976, 0.27564981, 0.27568514, 0.27677623,
       0.27731231, 0.28292115, 0.28756998, 0.29857415, 0.30803208,
       0.31099195, 0.31429423, 0.31870444, 0.33174554, 0.33451058,
       0.34807982, 0.35268308, 0.36018146, 0.39284157, 0.40450512,
       0.40645432, 0.41780758, 0.4530047 , 0.45385633, 0.45814523,
       0.50296241, 0.53778141, 0.5612601 , 0.56273718, 0.57409713,
       0.5821608 , 0.58695028, 0.60416289, 0.60469713, 0.60622912,
       0.63074843, 0.63120503, 0.63294484, 0.63938759, 0.65167301,
       0.65192331, 0.66981468, 0.70818203, 0.70902775, 0.72112468,
       0.72918187, 0.7465638 , 0.75063729, 0.75369958, 0.77261

#### 27. Проверить, одинаковы ли 2 numpy массива

In [92]:
s1 = np.array([1,2,3])
s2 = np.array([1,2,3])

In [93]:
np.allclose(s1,s2)

True

#### 28. Сделать массив неизменяемым

In [96]:
v = np.zeros(10).flags.writeable = False

#### 29. Найти n наибольших значений в массиве

In [98]:
v = np.arange(10000)
np.random.shuffle(v)

In [99]:
n = 10
v[np.argpartition(-v,n)[:n]]

array([9992, 9999, 9995, 9994, 9998, 9997, 9991, 9996, 9993, 9990])

#### 30. Заменить максимальный элемент на ноль

In [100]:
v = np.random.random(10)
v[v.argmax()] = 0

In [101]:
v

array([0.25513185, 0.75013217, 0.71377584, 0.        , 0.37839512,
       0.73297854, 0.61764495, 0.52707851, 0.85127846, 0.39408938])

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [104]:
v = np.zeros((10,10), [('x',float),('y',float)])
v['x'], v['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))

In [105]:
v

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [106]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)

In [107]:
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [109]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [110]:
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [9]:
ar1 = np.arange(100)

In [10]:
ar2 = np.random.uniform(0,100)

In [11]:
num = (np.abs(ar1-ar2)).argmin()

In [12]:
ar1[num]

58

#### 36. Преобразовать массив из float в int

In [18]:
ar = np.arange(10, dtype=np.float32)

In [19]:
ar = ar.astype(np.int32, copy=False)

In [20]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 37. Каков эквивалент функции enumerate для numpy массивов?

#### 38. Случайно расположить p элементов в 2D массив

#### 39. Отнять среднее из каждой строки в матрице

In [24]:
m1 = np.random.rand(5, 10)

In [26]:
m2 = m1 - m1.mean(axis=1, keepdims=True)

In [27]:
m2

array([[-0.0880916 ,  0.43195888, -0.30524011, -0.37868243, -0.22514716,
         0.15994644, -0.01871217,  0.2024276 , -0.3351975 ,  0.55673806],
       [-0.30207019, -0.00118284,  0.22245977, -0.10779928, -0.13682592,
         0.35474035, -0.416361  , -0.23195473,  0.48151933,  0.13747451],
       [ 0.36207626, -0.03642372,  0.29685598, -0.41969792, -0.22523885,
         0.30600113,  0.21248159, -0.17084866, -0.03349196, -0.29171384],
       [ 0.21645062, -0.08033326, -0.00174824,  0.05345542,  0.25977016,
         0.11995572, -0.01004923, -0.5582971 ,  0.15187854, -0.15108263],
       [ 0.5343676 , -0.29444869,  0.43660451, -0.24446294, -0.29458106,
        -0.00735045, -0.2848615 ,  0.39375565,  0.02359636, -0.26261948]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [33]:
ar1 = np.random.randint(0,20,(3,3))

In [34]:
ar1[ar1[:,0].argsort()]

array([[ 2, 13,  5],
       [ 3, 15, 19],
       [ 9, 19, 18]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям